### PR TITLE
render.js  ∆  Swap out headless browser for a more current option.

### PR DESCRIPTION
**Pull request by ajar**
Sample PNGs below. Moved from Nightmare to Puppeteer as PhantomJS has been deprecated.

### CODE REVIEW

**Comment by ajar** [comment]
Updated the `README.md` also. PDFs look good, same as PNG as far as the dimensions go.

**Comment by ajar** [comment]
@LunaUrsa @LunarUrsan @reality Hey, please see the changes implemented here and merge in when you can. Just bug-fixing, but PDF generation has been added (or re-added?) just as you'd expect it to work. Thank you!

**Comment by LunaUrsa** [comment]
Tested and this works great, thank you!

**Comment by LunaUrsa** [comment]
Okay turns out maybe not:

The PDF and HTML files work fine, and half of the PNG files are fine, but certain PNG outputs don't have any text.

EG:

image

**Comment by LunaUrsa** [comment]
Only RU, CS, PL and IT are affected

The Italian version (that i recently added) has the title, but nothing else?
image

This is not happening because some drug names appear on two lines

**Pull request merged**
